name: Daily Project Runs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/IBIT_Call_Monitor/scripts/requirements.txt
          
      - name: Run IBIT Call Monitor
        run: |
          python projects/IBIT_Call_Monitor/scripts/main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/results/
          git commit -m "Update results $(date +'%Y-%m-%d')" || exit 0
          git push 