name: Daily IBIT Long Leap Call Monitor - EOD

on:
  schedule:
    # Run Monday-Friday at 9:00 PM UTC (4:00 PM EST - After Market Close)
    # This accounts for both EST (UTC-5) and EDT (UTC-4) automatically
    - cron: '0 21 * * 1-5'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Allow pushing changes to repository

jobs:
  run-ibit-monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd projects/IBIT_Call_Monitor/scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run IBIT Long Leap Call Monitor with Market Validation
        run: |
          cd projects/IBIT_Call_Monitor/scripts
          python main.py
          
      - name: Commit and push if data collected
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action [EOD Long Leap Monitor]"
          
          # Add both data files
          git add projects/IBIT_Call_Monitor/data/ibit_calls.csv docs/projects/IBIT_Call_Monitor/data/ibit_calls.csv || true
          
          # Only commit if there are changes (market was open)
          if git diff --staged --quiet; then
            echo "✅ No changes to commit - Market was likely closed today"
          else
            git commit -m "📈 EOD IBIT Long Leap Call data update - $(TZ='America/New_York' date '+%Y-%m-%d %I:%M %p EST')"
            echo "🚀 Pushing updated data to repository"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 